apiVersion: v1
kind: Service
metadata:
  name: explorer
spec:
  type: ClusterIP
  selector:
    app: explorer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: explorer
