apiVersion: v1
kind: Service
metadata:
  name: explorer-db
spec:
  type: ClusterIP
  selector:
    app: explorer-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: pgsql
