# Default values for explorer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceAccount:
  name: "explorerappsa"

apps:
  explorer:
    repository: hyperledger/explorer
    tag: "1.1.2"
    vaultRole: explorerapp
    connectionProfiles:
      - networkName: wbp_demo_network
        profileFileName: wbpNetwork.json
        environment: dev
        ## Orderer and Peer ca file path without file name
        ordererCAPath: /opt/explorer/app/platform/fabric/crypto-config/ordererOrganizations/arun-walmart/tls
        peerCAPath: /opt/explorer/app/platform/fabric/crypto-config/peerOrganizations/arun-carrier/tls
        userID: exploreradmin
      
    env:
      - name: DATABASE_HOST
        value: explorer-db
      - name: LOG_LEVEL_APP
        value: debug
      - name: LOG_LEVEL_DB
        value: debug
      - name: LOG_LEVEL_CONSOLE
        value: info
      - name: LOG_CONSOLE_STDOUT
        value: "true"
      - name: DISCOVERY_AS_LOCALHOST
        value: "false"

  explorer_db:
    repository: hyperledger/explorer-db
    tag: "1.1.2"
    env:
      - name: DATABASE_DATABASE
        value: fabricexplorer
      - name: DATABASE_USERNAME
        value: admin
      - name: DATABASE_PASSWORD
        value: password
