---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: connection-profile
  labels:
    app.kubernetes.io/name: connection-profile
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
