---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-db
  labels:
    app.kubernetes.io/name: explorer-db
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
